apiVersion: v1
kind: Service
metadata:
  name: my-kube-deployment
spec:
  type: LoadBalancer  
  selector:
    app: my-kube-app  
  ports:
    - protocol: TCP
      port: 8082  
      targetPort: 3000  
